### ISSUE TITLE
issue running example

### ISSUE THREAD

**Issue by chris-desjardins** [TviNet/NetSolP-1.0#1]
Hi, When I try to run the example command I get a "file not found" error:

```
~/NetSolP-1.0/PredictionServer$ python predict.py --FASTA_PATH ./test_fasta.fasta --OUTPUT_PATH ./test_preds.csv --MODEL_TYPE ESM12 --PREDICTION_TYPE S
3
Doing Solubility
Model 0
Traceback (most recent call last):
  File "predict.py", line 178, in <module>
    get_preds(args)
  File "predict.py", line 92, in get_preds
    pred_df = get_preds_split(i, embed_dataloader, args, "Solubility", test_df)
  File "predict.py", line 30, in get_preds_split
    ort_sessions = [onnxruntime.InferenceSession(mp, sess_options=opts) for mp in model_paths]
  File "predict.py", line 30, in <listcomp>
    ort_sessions = [onnxruntime.InferenceSession(mp, sess_options=opts) for mp in model_paths]
  File "/home/chris_desjardins/miniconda3/envs/jup-ac/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/chris_desjardins/miniconda3/envs/jup-ac/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from ./models/Solubility_ESM12_0_quantized.onnx failed:Load model ./models/Solubility_ESM12_0_quantized.onnx failed. File doesn't exist
```

When I look in the models folder, there aren't any .onnx files. Should they be there? Or are there instructions on how to build them? I was hoping to use your "Distilled" model. Thanks.

**Comment by teevee112** [comment]
Hi, the download tab on the webserver page https://services.healthtech.dtu.dk/services/NetSolP-1.0/ should allow you to download all the models and the associated code.

**Comment by chris-desjardins** [comment]
Ah, thank you, I misunderstood the github readme.
